### ISSUE TITLE
Angular 8.0, marker moves when zooming

### ISSUE THREAD

**Issue by MarkRaasch** [bluehalo/ngx-leaflet#232] opened 2019-07-08 16:50 UTC
In Angular 8.0, using ngx-leaflet 6.0.1, the marker position moves significantly when zooming in/zooming out of the map. 

The marker is almost never as accurate as you would expect.  It is close to accurate at lower zoom levels.  However, when zooming out, the marker moves and it not close at all to the desired location (i.e. several hundred feet away).

This was functioning as expected in Angular 7.0 using ngx-leaflet 5.0.2.  

After upgrading to Angular 8.0, the problem was first observed.  Upgrading to ngx-leaflet 6.0.1 did not resolve the issue.

Here is some code we are using:

 this.options = {
      layers: [
        tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors' })
      ],
      zoom: 13,
      center:  latLng(Latitude, Longitude)
    };

We are dynamically adding markers in a loop:

 let marker: Marker = new Marker(Latitude, Longitude], {
        title: mapInput.DisplayName,
        icon: icon({
          iconUrl: 'xyz.png',
          shadowUrl: 'ys..png'
        })
      }).on('click', function (e) {
                // click event handler
      });

**Comment by reblace** [comment] 2019-07-10 22:08
I tried reproducing this but wasn’t able to. Can you provide a link to a
git repository that reproduces the issue?

**Comment by reblace** [comment] 2019-07-11 19:49
Can you make sure your anchor point is being correctly specified. The anchor point depends on where the "point" or centerpoint of your marker is. If it isn't specified, that may explain why it appears to be moving around.

```
const newMarker = marker([ 46.879966, -121.726909], {
	icon: icon({
		iconSize: [ 25, 41 ],
		iconAnchor: [ 13, 41 ],
		iconUrl: 'xyz.png',
		shadowUrl: 'ys.png'
	})
});
```

**Comment by MarkRaasch** [comment] 2019-07-11 20:16
Thank you for the information.With Angular 7 this was not necessary but worked as expected.With angular 8 we stumbled across this solution and it works and was required.MarkOn Jul 11, 2019 2:49 PM, Ryan Blace <notifications@github.com> wrote:Can you make sure your anchor point is being correctly specified. The anchor point depends on where the "point" or centerpoint of your marker is. If it isn't specified, that may explain why it appears to be moving around.
const newMarker = marker([ 46.879966, -121.726909], {
	icon: icon({
		iconSize: [ 25, 41 ],
		iconAnchor: [ 13, 41 ],
		iconUrl: 'xyz.png',
		shadowUrl: 'ys.png'
	})
});

**Comment by reblace** [comment] 2019-07-23 12:42
Closing since the issue was resolved.

**Closed as completed by reblace** 2019-07-23 12:42 UTC
