### ISSUE TITLE
 TypeError: Cannot read property 'off' of null when navigate out of map with  [leafletLayersControl]

### ISSUE THREAD

**Issue by shlomir** [bluehalo/ngx-leaflet#88] opened 2017-11-02 14:31 UTC
Environment:
"@asymmetrik/ngx-leaflet": "^2.5.0",
 "@types/leaflet": "^1.2.1",
   "leaflet": "^1.2.0"

When navigate out of a map, en error is rising :

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'off' of null
TypeError: Cannot read property 'off' of null
    at NewClass.removeLayer (leaflet-src.js:4855)
    at leaflet-control-layers.wrapper.js:39
    at DefaultKeyValueDiffer.webpackJsonp.../../../core/@angular/core.es5.js.DefaultKeyValueDiffer.forEachRemovedItem (core.es5.js:7642)
    at LeafletControlLayersWrapper.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.wrapper.js.LeafletControlLayersWrapper.applyChanges (leaflet-control-layers.wrapper.js:38)
    at LeafletControlLayersWrapper.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.wrapper.js.LeafletControlLayersWrapper.applyBaseLayerChanges (leaflet-control-layers.wrapper.js:18)
    at LeafletLayersControlDirective.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.js.LeafletLayersControlDirective.updateLayers (leaflet-control-layers.directive.js:71)
    at LeafletLayersControlDirective.set [as layersControlConfig] (leaflet-control-layers.directive.js:43)
    at LeafletLayersControlDirective.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.js.LeafletLayersControlDirective.ngOnDestroy (leaflet-control-layers.directive.js:58)
    at callProviderLifecycles (core.es5.js:11208)
    at callElementProvidersLifecycles (core.es5.js:11177)
    at NewClass.removeLayer (leaflet-src.js:4855)
    at leaflet-control-layers.wrapper.js:39
    at DefaultKeyValueDiffer.webpackJsonp.../../../core/@angular/core.es5.js.DefaultKeyValueDiffer.forEachRemovedItem (core.es5.js:7642)
    at LeafletControlLayersWrapper.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.wrapper.js.LeafletControlLayersWrapper.applyChanges (leaflet-control-layers.wrapper.js:38)
    at LeafletControlLayersWrapper.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.wrapper.js.LeafletControlLayersWrapper.applyBaseLayerChanges (leaflet-control-layers.wrapper.js:18)
    at LeafletLayersControlDirective.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.js.LeafletLayersControlDirective.updateLayers (leaflet-control-layers.directive.js:71)
    at LeafletLayersControlDirective.set [as layersControlConfig] (leaflet-control-layers.directive.js:43)
    at LeafletLayersControlDirective.webpackJsonp.../../../../@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.js.LeafletLayersControlDirective.ngOnDestroy (leaflet-control-layers.directive.js:58)
    at callProviderLifecycles (core.es5.js:11208)
    at callElementProvidersLifecycles (core.es5.js:11177)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at zone.js:873
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)

From debugging, it reproduced only when I got  [leafletLayersControl].
leaflet-control-layers.wrapper.js is trying to remove layer with currentValue = null... (line 39)

Is there any workaround or its a bug to fix?

Thanks

**Comment by reblace** [comment] 2017-11-02 15:26
I'll take a look in a little while. You could go to v2.4 temporarily. I added some logic to 2.5 to remove layers and the map when things are destroyed and it looks like I need to be more careful about not removing things that are already removed (or catching errors).

Also, thanks for catching this!

**Comment by reblace** [comment] 2017-11-03 15:41
Just a status update. I can easily reproduce this. So, I'll have a patch soon that should address these issues. As I said, just use 2.4.x for now and when I push a patch for 2.5.x I'll update this thread. Hopefully this weekend.

**Comment by reblace** [comment] 2017-11-04 20:29
Just FYI - this issue was actually introduced in v2.2.x

This should be fixed in 2.5.1, let me know if it's still an issue after you update.

**Closed as completed by reblace** 2017-11-04 20:29 UTC
Labels: bug

**Comment by ayyash** [comment] 2019-03-02 16:12
Curious, what was the issue? now I get ` Uncaught (in promise): TypeError: Cannot read property 'remove' of undefined` when I navigate away from page, but the thing is, I have a similar map on another route that is not facing any issues, I am quite perplexed (the only difference is one waits for the center to be set before showing, and the other shows a static center)

"Edit: the other difference is that the one that breaks, I add no markers on it"
```
core.js:15714 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'remove' of undefined
TypeError: Cannot read property 'remove' of undefined
    at LeafletLayerDirective.push../node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-layer.directive.js.LeafletLayerDirective.ngOnDestroy (leaflet-layer.directive.js:35)
    at callProviderLifecycles (core.js:22324)
    at callElementProvidersLifecycles (core.js:22292)
    at callLifecycleHooksChildrenFirst (core.js:22282)
    at destroyView (core.js:23344)
    at callViewAction (core.js:23470)
    at execEmbeddedViewsAction (core.js:23413)
    at destroyView (core.js:23342)
    at callViewAction (core.js:23470)
    at execComponentViewsAction (core.js:23392)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)
```

**Comment by ayyash** [comment] 2019-03-02 16:50
Hm, again, I missed what I was doing so wrong, turned out I was assigning a [leafletLayer]="location" but never really creating a value for it, removed it, now it works

**Comment by beshad** [comment] 2020-08-04 01:30
i am experiencing the same issue here, below error when trying to navigate away from map component (this.router.navigate(['/map', this.site.id], { state: { data: this.site } }))
```
core.js:6185 ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_targets' of null
TypeError: Cannot read property '_targets' of null
    at NewClass.removeInteractiveTarget (leaflet-src.js:6590)
    at NewClass._removePath (leaflet-src.js:12847)
    at NewClass.onRemove (leaflet-src.js:7862)
    at NewClass.removeLayer (leaflet-src.js:6692)
    at NewClass.eachLayer (leaflet-src.js:6904)
    at NewClass.onRemove (leaflet-src.js:6892)
    at NewClass.removeLayer (leaflet-src.js:6692)
    at leaflet-layers.directive.js:67
    at DefaultIterableDiffer.forEachRemovedItem (core.js:28218)
    at leaflet-layers.directive.js:66
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)
defaultErrorLogger @ core.js:6185
handleError @ core.js:6238
next @ core.js:42213
schedulerFn @ core.js:36889
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:36851
(anonymous) @ core.js:41326
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:41122
onHandleError @ core.js:41323
handleError @ zone-evergreen.js:368
runGuarded @ zone-evergreen.js:136
api.microtaskDrainDone @ zone-evergreen.js:670
drainMicroTaskQueue @ zone-evergreen.js:576
invokeTask @ zone-evergreen.js:484
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647
13:19:30.692 zone-evergreen.js:1632 [Violation] 'click' handler took 227ms
13:19:41.886 client:55 [WDS] App updated. Recompiling...
13:19:42.414 client:55 [WDS] App updated. Recompiling...
```
strange thing is that the exact same router navigate works form another component (angular dialog #1) but i can't navigate to any other component from the #2 dialog. i have mutiple overlays and one happens to be the most complicated one with several geo.json layers etc. when i UNCHECK this from the layer control  before naviating away then it's all good but doens't work that overlay is visible on map. i use a service to bring in the overlays to map. here is the code which doesn't work (dialog component #1):
```
  calibrationFinish() {
    this._storageService.asPromisable().set('monitor', this.screen).then(result => {
      if (result) {
        this.dialogRef.close(result)
        this.calibrationDataService.sendCalibrationData(result)
        if (this.site) {
          this.router.navigate(['/map', this.site.id], { state: { data: this.site } })
        } else {
          this._snackBar.open('Screen is calibrated successfully.', 'dismiss', {
            duration: 2000,
          });
        }
      }
    })
  }
```

and this works (dialog component #2)
```
  zoomTrueview(site: Site): void {
    this.store.dispatch(new AddSite(site))
    this.router.navigate(['/map', site.id], { state: { data: site } })
    this.dialogRef.close();
  }
```

thanks for the help

**Comment by beshad** [comment] 2020-08-04 20:15
i can eliminate the error two ways, one by unchecking oen of the layers and the other by amending the router navigate to: this.router.navigate(['map', site.id], { state: { data: site } }) by removing the forward-slash. i am still puzzled why same code and that one layer works fine from one component and not from the other.  the working component is child of map component and troublesome component is not the map child

**Comment by reblace** [comment] 2020-08-04 22:30
Can you tell me what version you're using (leaflet and ngx-leaflet)?

I'm curious to see what code's on leaflet-layers.directive.js:67 and what's going on in Leaflet.

I might be able to just add a simple defensive code check there to mitigate this.

**Comment by beshad** [comment] 2020-08-04 23:11
here is my dependencies: 
```
"dependencies": {
    "@angular/animations": "~9.0.5",
    "@angular/cdk": "^9.1.1",
    "@angular/common": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/forms": "~9.0.5",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/router": "~9.0.5",
    "@angular/service-worker": "~9.0.5",
    "@asymmetrik/ngx-leaflet": "^7.0.1",
    "@fortawesome/angular-fontawesome": "^0.6.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@ngrx/store": "^9.2.0",
    "@types/leaflet-rotatedmarker": "^0.2.1",
    "angular-svg-icon": "^9.1.0",
    "bootstrap": "^4.5.0",
    "leaflet": "^1.6.0",
    "leaflet-rotatedmarker": "^0.2.0",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^5.5.0",
    "ngx-localstorage": "^3.1.0",
    "openseadragon": "^2.4.2",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
```
and i use a service to bring in several layers of geojson object. the one that happens to break navigating away (until its unchecked from the control) is happen to be the largest one: 

in the layer service i have this:
````
  public readonly proposedRoutes: Layer = L.geoJSON(ProposedRoutes as any, {
    onEachFeature: (feature, layer) => {

      let label: string = `${feature.properties.display}`;

      if (layer instanceof L.Polyline) {

        layer.setStyle({
          color: feature.properties.data.color,
          stroke: true,
          weight: feature.properties.data.weight,
          opacity: 1,
          dashArray: feature.properties.data.dashArray ? '9' : '0',
        }).bindTooltip(label,
          {
            permanent: false,
            opacity: 0.9,
            direction: "auto",
            className: "route-labels"
          }).openTooltip()
      }
    }
  })
```
would complexity of a geojson layer make layers removal different?

**Comment by SecuritasMachina** [comment] 2020-12-07 13:43
Any update on this? I receive same error using 1.7.1
