### ISSUE TITLE
Heat is not working if two maps are on same page

### ISSUE THREAD

**Issue by shashi5678** [bluehalo/ngx-leaflet#202] opened 2019-01-13 17:44 UTC
Heat is not working if two maps are on same page

**Comment by reblace** [comment] 2019-01-31 13:54
Can you provide an example that reproduces the problem?

**Comment by reblace** [comment] 2019-03-07 14:48
No example, so I'm going to close this. Usually the cause of this issue is when you add the same layers or controls to multiple maps. The map mutates layers and controls when they are added to the map, so you have to make sure to create new ones for each instance of a map you create.

**Closed as completed by reblace** 2019-03-07 14:48 UTC
