### ISSUE TITLE
issue on running the demo in Windows

### ISSUE THREAD

**Issue by zealitude** [bluehalo/ngx-leaflet#37] opened 2017-03-30 03:49 UTC
PS C:\Users\xxxx\Documents\angular2-leaflet> gulp dev
[11:45:27] Using gulpfile ~\Documents\angular2-leaflet\gulpfile.js
[11:45:27] Starting 'dev'...
[11:45:27] Starting 'validate-ts'...
[11:45:28] Finished 'validate-ts' after 847 ms
[11:45:28] Starting 'webpack-dev-server'...
[11:45:28] Starting 'watch-ts'...
[11:45:28] Finished 'watch-ts' after 27 ms
[11:45:28] [webpack] http://localhost:9000/webpack-dev-server/index.html
ts-loader: Using typescript@2.2.2
ts-loader: Using typescript@2.2.2
Hash: 3c13ce2d5cf40dab683c
Version: webpack 2.3.2
Time: 205ms
         Asset       Size  Chunks             Chunk Names
application.js  360 bytes       0  [emitted]  application
     vendor.js    6.28 kB       1  [emitted]  vendor

ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.

ERROR in ./src/demo/main.ts
Module build failed: error while parsing tsconfig.json

ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.

ERROR in ./src/demo/vendor.ts
Module build failed: error while parsing tsconfig.json
webpack: Failed to compile.

**Comment by reblace** [comment] 2017-03-30 04:03
You running on Windows? If so, I'll take a look to see if I'm doing anything that might cause cross-platform issues. I dev on OSX/Linux.

**Comment by zealitude** [comment] 2017-03-30 06:42
yes, windows :(

**Comment by reblace** [comment] 2017-03-30 15:16
I can't reproduce this issue yet (I don't have an easily accessible Windows PC), but I made a few changes to try to address the issue you're seeing.

Can you checkout the **windowsBuild** branch and see if the problem persists there?

There were two fixes, first I made a change to the way the path npm package is used, which can cause issues on Windows. Second, I added an explicit exclude and include to the tsconfig.json file. Which I think can cause problems with the latest ts-loader/typescript in some cases (though strangely not for me).

**Comment by zealitude** [comment] 2017-03-31 02:55
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> C:\xxx\www\angular\angular2-leaflet>git status
> On branch windowsBuild
> Your branch is up-to-date with 'origin/windowsBuild'.
> nothing to commit, working tree clean
> 
> C:\xxx\www\angular\angular2-leaflet>gulp dev
> [10:53:11] Using gulpfile C:\xxx\www\angular\angular2-leaflet\gulpfile.js
> [10:53:11] Starting 'dev'...
> [10:53:11] Starting 'validate-ts'...
> [10:53:11] Finished 'validate-ts' after 724 ms
> [10:53:11] Starting 'webpack-dev-server'...
> [10:53:12] Starting 'watch-ts'...
> [10:53:12] Finished 'watch-ts' after 26 ms
> [10:53:12] [webpack] http://localhost:9000/webpack-dev-server/index.html
> ts-loader: Using typescript@2.2.2
> ts-loader: Using typescript@2.2.2
> Hash: 3c13ce2d5cf40dab683c
> Version: webpack 2.3.2
> Time: 168ms
>          Asset       Size  Chunks             Chunk Names
> application.js  360 bytes       0  [emitted]  application
>      vendor.js    6.28 kB       1  [emitted]  vendor
> 
> ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.
> 
> ERROR in ./src/demo/main.ts
> Module build failed: error while parsing tsconfig.json
> 
> ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.
> 
> ERROR in ./src/demo/vendor.ts
> Module build failed: error while parsing tsconfig.json
> webpack: Failed to compile.

**Comment by reblace** [comment] 2017-03-31 03:31
Try editing ./tsconfig.json

**replace:**
```js
	"include": [
		"./src/**/*.ts"
	]
```

**with:**
```js
	"files": [
		"./src/demo/main.ts"
	]
```


See if you can get it past the issue with not listing files in tsconfig.json. The dev build shouldn't need the files to be specified in tsconfig.json, and it doesn't complain on *nix systems, so I'm not sure what's going on, but I've heard of this kind of issue before. Let me know if you have any luck. I also pushed the change to the branch if you just want to pull and try building again.

**Comment by reblace** [comment] 2017-04-02 22:36
I was able to reproduce this on Windows. With a minor tweak to the tsconfig.json, i was able to get past the error you're getting. But, then I found another issue related to ts-loader not honoring excluded files (eg. node_modules) on Windows. So, I'll keep looking into this. Might motivate me to migrate to using awesome-ts-loader since it sounds like that doesn't have the same issue.

**Comment by reblace** [comment] 2017-04-07 01:05
Another attempt at fixing it is merged to the 'develop' branch. You'll need to reinstall your node_modules. I migrated to awesome typescript loader, which doesn't have the same issues that ts-loader has with Windows. It works on my Windows 7 laptop.

**Comment by reblace** [comment] 2017-04-07 12:34
I merged the PR into the master branch, so you can check it out on either

**Comment by reblace** [comment] 2017-04-11 23:23
If @zealitude or anyone else can confirm this is working for them on other versions of Windows, I'll close the issue. I'll give it a few more days to see.

**Comment by tlofgren** [comment] 2017-04-12 16:01
I can confirm the latest version in master builds on Windows 7. I was getting the same errors as @zealitude before, but now both `gulp dev` and `gulp build` work just fine.

**Comment by reblace** [comment] 2017-04-12 17:35
Sweet. +1 for awesome-typescript-loader. Thanks for letting me know @tlofgren

**Closed as completed by reblace** 2017-04-12 17:35 UTC
