### ISSUE TITLE
TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by azizkhani** [bluehalo/ngx-leaflet#273] opened 2020-06-12 09:55 UTC
```
    
    ERROR in node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/base/leaflet-baselayers.directive.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/base/leaflet-baselayers.directive.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/control/leaflet-control-layers.directive.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-layers.directive.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-layers.directive.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
    
```

**Comment by reblace** [comment] 2020-06-13 14:39
I think this is caused by: https://github.com/microsoft/TypeScript/issues/33939 - It's a backward compatibility with newer Typescript versions.

I suspect your solution is to upgrade Typescript and ng cli to make sure you're running the latest CLI and at least typescript 3.7+.

If not, you should post your package.json

**Comment by cranfillkd** [comment] 2020-06-29 14:08
Updating to Angular 9 fixed this for me. https://update.angular.io/

**Comment by reblace** [comment] 2020-06-29 14:47
Closing as upgrading Angular CLI is the fix.

**Closed as completed by reblace** 2020-06-29 14:47 UTC
